#include "LTDC.h"
#include "stm32f429xx.h"

#include <stdint.h>

uint16_t DISPLAY [76800];

void CS_On(){
	GPIOC->BSRR |= GPIO_BSRR_BS2;
}

void CS_Off(){
	GPIOC->BSRR |= GPIO_BSRR_BR2;
}

void WRX_On(){
	GPIOD->BSRR |= GPIO_BSRR_BS13;
}

void WRX_Off(){
	GPIOD->BSRR |= GPIO_BSRR_BR13;
}

void LCD_WriteCommand(uint8_t LCD_Reg){
	WRX_Off();
	CS_Off();
	SPI5->DR = LCD_Reg;
	while(!(SPI5->SR & SPI_SR_RXNE));
	while((SPI5->SR & SPI_SR_BSY));
	CS_On();
}

void LCD_WriteData(uint8_t LCD_data){
	WRX_On();
	CS_Off();
	SPI5->DR = LCD_data;
	while(!(SPI5->SR & SPI_SR_RXNE));
	while((SPI5->SR & SPI_SR_BSY));
	CS_On();
	
}

void LTDC_Init(){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOGEN;
	
	//B5
	GPIOA->MODER &= ~GPIO_MODER_MODER3_Msk;
	GPIOA->MODER |= GPIO_MODER_MODER3_1;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3_1 | GPIO_OSPEEDER_OSPEEDR3_0;
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFSEL3_Msk;
	GPIOA->AFR[0] |= 14U << GPIO_AFRL_AFSEL3_Pos;

	//VSYNK
	GPIOA->MODER &= ~GPIO_MODER_MODER4_Msk;
	GPIOA->MODER |= GPIO_MODER_MODER4_1;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR4_1 | GPIO_OSPEEDER_OSPEEDR4_0;
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFSEL4_Msk;
	GPIOA->AFR[0] |= 14U << GPIO_AFRL_AFSEL4_Pos;
	
	//G2
	GPIOA->MODER &= ~GPIO_MODER_MODER6_Msk;
	GPIOA->MODER |= GPIO_MODER_MODER6_1;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6_1 | GPIO_OSPEEDER_OSPEEDR6_0;
	GPIOA->AFR[0] &= ~GPIO_AFRL_AFSEL6_Msk;
	GPIOA->AFR[0] |= 14U << GPIO_AFRL_AFSEL6_Pos;
	
	//R4
	GPIOA->MODER &= ~GPIO_MODER_MODER11_Msk;
	GPIOA->MODER |= GPIO_MODER_MODER11_1;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11_1 | GPIO_OSPEEDER_OSPEEDR11_0;
	GPIOA->AFR[1] &= ~GPIO_AFRH_AFSEL11_Msk;
	GPIOA->AFR[1] |= 14U << GPIO_AFRH_AFSEL11_Pos;

	//R5
	GPIOA->MODER &= ~GPIO_MODER_MODER12_Msk;
	GPIOA->MODER |= GPIO_MODER_MODER12_1;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR12_1 | GPIO_OSPEEDER_OSPEEDR12_0;
	GPIOA->AFR[1] &= ~GPIO_AFRH_AFSEL12_Msk;
	GPIOA->AFR[1] |= 14U << GPIO_AFRH_AFSEL12_Pos;

	//R3
	GPIOB->MODER &= ~GPIO_MODER_MODER0_Msk;
	GPIOB->MODER |= GPIO_MODER_MODER0_1;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0_1 | GPIO_OSPEEDER_OSPEEDR0_0;
	GPIOB->AFR[0] &= ~GPIO_AFRL_AFSEL0_Msk;
	GPIOB->AFR[0] |= 14U << GPIO_AFRL_AFSEL0_Pos;

	//R6
	GPIOB->MODER &= ~GPIO_MODER_MODER1_Msk;
	GPIOB->MODER |= GPIO_MODER_MODER1_1;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR1_1 | GPIO_OSPEEDER_OSPEEDR1_0;
	GPIOB->AFR[0] &= ~GPIO_AFRL_AFSEL1_Msk;
	GPIOB->AFR[0] |= 14U << GPIO_AFRL_AFSEL1_Pos;
	
	//B6
	GPIOB->MODER &= ~GPIO_MODER_MODER8_Msk;
	GPIOB->MODER |= GPIO_MODER_MODER8_1;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8_1 | GPIO_OSPEEDER_OSPEEDR8_0;
	GPIOB->AFR[1] &= ~GPIO_AFRH_AFSEL8_Msk;
	GPIOB->AFR[1] |= 14U << GPIO_AFRH_AFSEL8_Pos;

	//B7
	GPIOB->MODER &= ~GPIO_MODER_MODER9_Msk;
	GPIOB->MODER |= GPIO_MODER_MODER9_1;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_1 | GPIO_OSPEEDER_OSPEEDR9_0;
	GPIOB->AFR[1] &= ~GPIO_AFRH_AFSEL9_Msk;
	GPIOB->AFR[1] |= 14U << GPIO_AFRH_AFSEL9_Pos;

	//G4
	GPIOB->MODER &= ~GPIO_MODER_MODER10_Msk;
	GPIOB->MODER |= GPIO_MODER_MODER10_1;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_1 | GPIO_OSPEEDER_OSPEEDR10_0;
	GPIOB->AFR[1] &= ~GPIO_AFRH_AFSEL10_Msk;
	GPIOB->AFR[1] |= 14U << GPIO_AFRH_AFSEL10_Pos;

	//G5
	GPIOB->MODER &= ~GPIO_MODER_MODER11_Msk;
	GPIOB->MODER |= GPIO_MODER_MODER11_1;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11_1 | GPIO_OSPEEDER_OSPEEDR11_0;
	GPIOB->AFR[1] &= ~GPIO_AFRH_AFSEL11_Msk;
	GPIOB->AFR[1] |= 14U << GPIO_AFRH_AFSEL11_Pos;

	//CSX
	GPIOC->MODER &= ~GPIO_MODER_MODER2_Msk;
	GPIOC->MODER |= GPIO_MODER_MODER2_0;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR2_1 | GPIO_OSPEEDER_OSPEEDR2_0;

	//HSYNK
	GPIOC->MODER &= ~GPIO_MODER_MODER6_Msk;
	GPIOC->MODER |= GPIO_MODER_MODER6_1;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6_1 | GPIO_OSPEEDER_OSPEEDR6_0;
	GPIOC->AFR[0] &= ~GPIO_AFRL_AFSEL6_Msk;
	GPIOC->AFR[0] |= 14U << GPIO_AFRL_AFSEL6_Pos;

	//G6
	GPIOC->MODER &= ~GPIO_MODER_MODER7_Msk;
	GPIOC->MODER |= GPIO_MODER_MODER7_1;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR7_1 | GPIO_OSPEEDER_OSPEEDR7_0;
	GPIOC->AFR[0] &= ~GPIO_AFRL_AFSEL7_Msk;
	GPIOC->AFR[0] |= 14U << GPIO_AFRL_AFSEL7_Pos;
	
	//R2
	GPIOC->MODER &= ~GPIO_MODER_MODER10_Msk;
	GPIOC->MODER |= GPIO_MODER_MODER10_1;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_1 | GPIO_OSPEEDER_OSPEEDR10_0;
	GPIOC->AFR[1] &= ~GPIO_AFRH_AFSEL10_Msk;
	GPIOC->AFR[1] |= 14U << GPIO_AFRH_AFSEL10_Pos;
	
	//G7
	GPIOD->MODER &= ~GPIO_MODER_MODER3_Msk;
	GPIOD->MODER |= GPIO_MODER_MODER3_1;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3_1 | GPIO_OSPEEDER_OSPEEDR3_0;
	GPIOD->AFR[0] &= ~GPIO_AFRL_AFSEL3_Msk;
	GPIOD->AFR[0] |= 14U << GPIO_AFRL_AFSEL3_Pos;
	
	//B2
	GPIOD->MODER &= ~GPIO_MODER_MODER6_Msk;
	GPIOD->MODER |= GPIO_MODER_MODER6_1;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6_1 | GPIO_OSPEEDER_OSPEEDR6_0;
	GPIOD->AFR[0] &= ~GPIO_AFRL_AFSEL6_Msk;
	GPIOD->AFR[0] |= 14U << GPIO_AFRL_AFSEL6_Pos;
	
	//WRX_DCX
	GPIOD->MODER &= ~GPIO_MODER_MODER13_Msk;
	GPIOD->MODER |= GPIO_MODER_MODER13_0;
	GPIOD->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR13_1 | GPIO_OSPEEDER_OSPEEDR13_0;
	
	//DCX_SCL
	GPIOF->MODER &= ~GPIO_MODER_MODER7_Msk;
	GPIOF->MODER |= GPIO_MODER_MODER7_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR7_1 | GPIO_OSPEEDER_OSPEEDR7_0;
	GPIOF->AFR[0] &= ~GPIO_AFRL_AFSEL7_Msk;
	GPIOF->AFR[0] |= 5U << GPIO_AFRL_AFSEL7_Pos;
	
	//DCX_SDA
	GPIOF->MODER &= ~GPIO_MODER_MODER9_Msk;
	GPIOF->MODER |= GPIO_MODER_MODER9_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_1 | GPIO_OSPEEDER_OSPEEDR9_0;
	GPIOF->AFR[1] &= ~GPIO_AFRH_AFSEL9_Msk;
	GPIOF->AFR[1] |= 5U << GPIO_AFRH_AFSEL9_Pos;
	
	//DE
	GPIOF->MODER &= ~GPIO_MODER_MODER10_Msk;
	GPIOF->MODER |= GPIO_MODER_MODER10_1;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_1 | GPIO_OSPEEDER_OSPEEDR10_0;
	GPIOF->AFR[1] &= ~GPIO_AFRH_AFSEL10_Msk;
	GPIOF->AFR[1] |= 14U << GPIO_AFRH_AFSEL10_Pos;
	
	//R7
	GPIOG->MODER &= ~GPIO_MODER_MODER6_Msk;
	GPIOG->MODER |= GPIO_MODER_MODER6_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6_1 | GPIO_OSPEEDER_OSPEEDR6_0;
	GPIOG->AFR[0] &= ~GPIO_AFRL_AFSEL6_Msk;
	GPIOG->AFR[0] |= 14U << GPIO_AFRL_AFSEL6_Pos;
	
	//CLK
	GPIOG->MODER &= ~GPIO_MODER_MODER7_Msk;
	GPIOG->MODER |= GPIO_MODER_MODER7_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR6_1 | GPIO_OSPEEDER_OSPEEDR6_0;
	GPIOG->AFR[0] &= ~GPIO_AFRL_AFSEL7_Msk;
	GPIOG->AFR[0] |= 14U << GPIO_AFRL_AFSEL7_Pos;
	
	//G3
	GPIOG->MODER &= ~GPIO_MODER_MODER10_Msk;
	GPIOG->MODER |= GPIO_MODER_MODER10_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR10_1 | GPIO_OSPEEDER_OSPEEDR10_0;
	GPIOG->AFR[1] &= ~GPIO_AFRH_AFSEL10_Msk;
	GPIOG->AFR[1] |= 14U << GPIO_AFRH_AFSEL10_Pos;
	
	//B3
	GPIOG->MODER &= ~GPIO_MODER_MODER11_Msk;
	GPIOG->MODER |= GPIO_MODER_MODER11_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR11_1 | GPIO_OSPEEDER_OSPEEDR11_0;
	GPIOG->AFR[1] &= ~GPIO_AFRH_AFSEL11_Msk;
	GPIOG->AFR[1] |= 14U << GPIO_AFRH_AFSEL11_Pos;
	
	//B4
	GPIOG->MODER &= ~GPIO_MODER_MODER12_Msk;
	GPIOG->MODER |= GPIO_MODER_MODER12_1;
	GPIOG->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR12_1 | GPIO_OSPEEDER_OSPEEDR12_0;
	GPIOG->AFR[1] &= ~GPIO_AFRH_AFSEL12_Msk;
	GPIOG->AFR[1] |= 14U << GPIO_AFRH_AFSEL12_Pos;
	
	RCC->PLLSAICFGR &= ~RCC_PLLSAICFGR_PLLSAIN_Msk;
	RCC->PLLSAICFGR |= 0xC0 << RCC_PLLSAICFGR_PLLSAIN_Pos;
	RCC->PLLSAICFGR &= ~RCC_PLLSAICFGR_PLLSAIR_Msk;
	RCC->PLLSAICFGR |= 0x03<< RCC_PLLSAICFGR_PLLSAIR_Pos;
	RCC->PLLSAICFGR |= 0x07 << RCC_PLLSAICFGR_PLLSAIQ_Pos;
	RCC->DCKCFGR &= ~RCC_DCKCFGR_PLLSAIDIVR_Msk;
	RCC->DCKCFGR |= 0b10 << RCC_DCKCFGR_PLLSAIDIVR_Pos;
	
	RCC->CR |= RCC_CR_PLLSAION;
	while(!(RCC->CR & RCC_CR_PLLSAIRDY));
	
	RCC->APB2ENR |= RCC_APB2ENR_SPI5EN;
	SPI5->CR1 &= ~SPI_CR1_DFF;
	SPI5->CR1 &= ~SPI_CR1_LSBFIRST;	
	SPI5->CR1 |= SPI_CR1_SSM;
	SPI5->CR1 |= SPI_CR1_SSI;
	SPI5->CR1 &= ~SPI_CR1_BR_Msk;
	SPI5->CR1 |= 0b100 << SPI_CR1_BR_Pos;
	SPI5->CR1 |= SPI_CR1_MSTR;
	SPI5->CR1 &= ~SPI_CR1_CPOL;
	SPI5->CR1 &= ~SPI_CR1_CPHA;
	SPI5->CR1 |= SPI_CR1_SPE;	
	
	
	 LCD_WriteCommand(0xCA);
  LCD_WriteData(0xC3);
  LCD_WriteData(0x08);
  LCD_WriteData(0x50);
  LCD_WriteCommand(LCD_POWERB);
  LCD_WriteData(0x00);
  LCD_WriteData(0xC1);
  LCD_WriteData(0x30);
  LCD_WriteCommand(LCD_POWER_SEQ);
  LCD_WriteData(0x64);
  LCD_WriteData(0x03);
  LCD_WriteData(0x12);
  LCD_WriteData(0x81);
  LCD_WriteCommand(LCD_DTCA);
  LCD_WriteData(0x85);
  LCD_WriteData(0x00);
  LCD_WriteData(0x78);
  LCD_WriteCommand(LCD_POWERA);
  LCD_WriteData(0x39);
  LCD_WriteData(0x2C);
  LCD_WriteData(0x00);
  LCD_WriteData(0x34);
  LCD_WriteData(0x02);
  LCD_WriteCommand(LCD_PRC);
  LCD_WriteData(0x20);
  LCD_WriteCommand(LCD_DTCB);
  LCD_WriteData(0x00);
  LCD_WriteData(0x00);
  LCD_WriteCommand(LCD_FRC);
  LCD_WriteData(0x00);
  LCD_WriteData(0x1B);
  LCD_WriteCommand(LCD_DFC);
  LCD_WriteData(0x0A);
  LCD_WriteData(0xA2);
  LCD_WriteCommand(LCD_POWER1);
  LCD_WriteData(0x10);
  LCD_WriteCommand(LCD_POWER2);
  LCD_WriteData(0x10);
  LCD_WriteCommand(LCD_VCOM1);
  LCD_WriteData(0x45);
  LCD_WriteData(0x15);
  LCD_WriteCommand(LCD_VCOM2);
  LCD_WriteData(0x90);
  LCD_WriteCommand(LCD_MAC);
  LCD_WriteData(0xC8);
  LCD_WriteCommand(LCD_3GAMMA_EN);
  LCD_WriteData(0x00);
  LCD_WriteCommand(LCD_RGB_INTERFACE);
  LCD_WriteData(0xC2);
  LCD_WriteCommand(LCD_DFC);
  LCD_WriteData(0x0A);
  LCD_WriteData(0xA7);
  LCD_WriteData(0x27);
  LCD_WriteData(0x04);

  /* colomn address set */
  LCD_WriteCommand(LCD_COLUMN_ADDR);
  LCD_WriteData(0x00);
  LCD_WriteData(0x00);
  LCD_WriteData(0x00);
  LCD_WriteData(0xEF);
  /* Page Address Set */
  LCD_WriteCommand(LCD_PAGE_ADDR);
  LCD_WriteData(0x00);
  LCD_WriteData(0x00);
  LCD_WriteData(0x01);
  LCD_WriteData(0x3F);
  LCD_WriteCommand(LCD_INTERFACE);
  LCD_WriteData(0x01);
  LCD_WriteData(0x00);
  LCD_WriteData(0x06);
  
  LCD_WriteCommand(LCD_GRAM);
  for(int i=0; i<201; i++);
  
  LCD_WriteCommand(LCD_GAMMA);
  LCD_WriteData(0x01);
  
  LCD_WriteCommand(LCD_PGAMMA);
  LCD_WriteData(0x0F);
  LCD_WriteData(0x29);
  LCD_WriteData(0x24);
  LCD_WriteData(0x0C);
  LCD_WriteData(0x0E);
  LCD_WriteData(0x09);
  LCD_WriteData(0x4E);
  LCD_WriteData(0x78);
  LCD_WriteData(0x3C);
  LCD_WriteData(0x09);
  LCD_WriteData(0x13);
  LCD_WriteData(0x05);
  LCD_WriteData(0x17);
  LCD_WriteData(0x11);
  LCD_WriteData(0x00);
  LCD_WriteCommand(LCD_NGAMMA);
  LCD_WriteData(0x00);
  LCD_WriteData(0x16);
  LCD_WriteData(0x1B);
  LCD_WriteData(0x04);
  LCD_WriteData(0x11);
  LCD_WriteData(0x07);
  LCD_WriteData(0x31);
  LCD_WriteData(0x33);
  LCD_WriteData(0x42);
  LCD_WriteData(0x05);
  LCD_WriteData(0x0C);
  LCD_WriteData(0x0A);
  LCD_WriteData(0x28);
  LCD_WriteData(0x2F);
  LCD_WriteData(0x0F);
  
  LCD_WriteCommand(LCD_SLEEP_OUT);
  for(int i=0; i<201; i++);
LCD_WriteCommand(LCD_DISPLAY_ON);
  /* GRAM start writing */
  LCD_WriteCommand(LCD_GRAM);
	
	RCC->APB2ENR |= RCC_APB2ENR_LTDCEN;
	
	//Тайминги
	
	LTDC->SSCR &= ~LTDC_SSCR_HSW_Msk;
	LTDC->SSCR |= 9 << LTDC_SSCR_HSW_Pos;
	LTDC->SSCR &= ~LTDC_SSCR_VSH_Msk;
	LTDC->SSCR |= 1 << LTDC_SSCR_VSH_Pos;
	
	LTDC->BPCR &= ~LTDC_BPCR_AHBP_Msk;
	LTDC->BPCR |= 0x1D << LTDC_BPCR_AHBP_Pos;
	LTDC->BPCR &= ~LTDC_BPCR_AVBP_Msk;
	LTDC->BPCR |= 3 << LTDC_BPCR_AVBP_Pos;
	
	LTDC->AWCR &= ~LTDC_AWCR_AAW_Msk;
	LTDC->AWCR |= 0x10D << LTDC_AWCR_AAW_Pos;
	LTDC->AWCR &= ~LTDC_AWCR_AAH_Msk;
	LTDC->AWCR |= 0x143 << LTDC_AWCR_AAH_Pos;
	
	LTDC->TWCR &= ~LTDC_TWCR_TOTALW_Msk;
	LTDC->TWCR |= 0x117 << LTDC_TWCR_TOTALW_Pos;
	LTDC->TWCR &= ~LTDC_TWCR_TOTALH_Msk;
	LTDC->TWCR |= 0x147 << LTDC_TWCR_TOTALH_Pos;
	
	//Цвет фона
	LTDC->BCCR = 0x0000;
	
	//НАСТРОЙКА СЛОЁВ
	//Размер слоя
	LTDC_Layer1->WHPCR &= ~LTDC_LxWHPCR_WHSPPOS_Msk;
	LTDC_Layer1->WHPCR |= 0x10D << LTDC_LxWHPCR_WHSPPOS_Pos;
	LTDC_Layer1->WHPCR &= ~LTDC_LxWHPCR_WHSTPOS_Msk;
	LTDC_Layer1->WHPCR |= 0x1E << LTDC_LxWHPCR_WHSTPOS_Pos;
	
	LTDC_Layer1->WVPCR &= ~LTDC_LxWVPCR_WVSPPOS_Msk;
	LTDC_Layer1->WVPCR |= 0x143 << LTDC_LxWVPCR_WVSPPOS_Pos;
	LTDC_Layer1->WVPCR &= ~LTDC_LxWVPCR_WVSTPOS_Msk;
	LTDC_Layer1->WVPCR |= 0x4 << LTDC_LxWVPCR_WVSTPOS_Pos;

	//Формат данных - RGB565
 	LTDC_Layer1->PFCR = 0b010;
	
	//Адресс буфера
	LTDC_Layer1->CFBAR = (uint32_t) DISPLAY;
	
	//Размер строк
		LTDC_Layer1->CFBLR  =0x01E001E3;
	//LTDC_Layer1->CFBLR &= ~LTDC_LxCFBLR_CFBP_Msk;
	//LTDC_Layer1->CFBLR |= 0x1E0 << LTDC_LxCFBLR_CFBP_Pos;
	//LTDC_Layer1->CFBLR &= ~LTDC_LxCFBLR_CFBLL_Msk;
	//LTDC_Layer1->CFBLR |= 0x1E3 << LTDC_LxCFBLR_CFBLL_Pos;
	
	LTDC_Layer1->WHPCR =0x010D001E;
	//LTDC_Layer1->WHPCR |= 0x10D << LTDC_LxWHPCR_WHSPPOS_Pos;
	//LTDC_Layer1->WHPCR |= 0x1E << LTDC_LxWHPCR_WHSTPOS_Pos;
	
	LTDC_Layer1->WVPCR =0x01430004;
	//LTDC_Layer1->WVPCR |= 0x143 << LTDC_LxWVPCR_WVSPPOS_Pos;
	//LTDC_Layer1->WVPCR |= 0x4 << LTDC_LxWVPCR_WVSTPOS_Pos;
	
	LTDC_Layer1->CACR = 0xFF;
	LTDC_Layer1->DCCR =0;
	LTDC_Layer1->BFCR =0;
	LTDC_Layer1->BFCR |= 4 << LTDC_LxBFCR_BF1_Pos;
	LTDC_Layer1->BFCR |= 5 << LTDC_LxBFCR_BF2_Pos;
	
	LTDC_Layer1->CFBLNR = 320;
	
	//Колличество строк
	//LTDC_Layer1->CFBLNR = 240;
	
	LTDC_Layer1->CR |= LTDC_LxCR_LEN;
	LTDC->SRCR |= LTDC_SRCR_VBR; //Обновление настроек слоя
	//LTDC->GCR |= LTDC_GCR_DEN;
	LTDC->GCR |= LTDC_GCR_LTDCEN;
}
