#include "stm32f429xx.h"
#include "RCC.h"
#include <stdint.h>

void RCC_Init(){
	
	FLASH->ACR = FLASH_ACR_PRFTEN;	
	FLASH->ACR &= ~FLASH_ACR_LATENCY_Msk;
	FLASH->ACR |= FLASH_ACR_LATENCY_5WS;
	
	RCC->CR |= RCC_CR_HSEON;									//Кварц (8)
	while(!(RCC->CR & RCC_CR_HSERDY));
	
	RCC->CFGR &= ~RCC_CFGR_PPRE2_Msk;
	RCC->CFGR |= 0b100 << RCC_CFGR_PPRE2_Pos; //APB2 AHB/2
	RCC->CFGR &= ~RCC_CFGR_PPRE1_Msk;
	RCC->CFGR |= 0b101 << RCC_CFGR_PPRE1_Pos;	//APB1 AHB/4
	
	RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC; 			//HSE --- PLL
	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLM_Msk;	
	RCC->PLLCFGR |= 8 << RCC_PLLCFGR_PLLM_Pos;	//   /4
	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLN_Msk;
	RCC->PLLCFGR |= 360 << RCC_PLLCFGR_PLLN_Pos;// *180
	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLQ_Msk;
	RCC->PLLCFGR |= 7 << RCC_PLLCFGR_PLLQ_Pos;  // 
	RCC->PLLCFGR &= ~RCC_PLLCFGR_PLLP;
	RCC->PLLCFGR |= 0b00 << RCC_PLLCFGR_PLLP_Pos;
	
	RCC->CR |= RCC_CR_PLLON;
	while(!(RCC->CR & RCC_CR_PLLRDY));
	
	RCC->CFGR |= RCC_CFGR_SW_1;
	RCC->CFGR &= ~RCC_CFGR_SW_0; // PLL --- AHB
	while(!((RCC->CFGR & RCC_CFGR_SWS_1) && (RCC->CFGR &= ~RCC_CFGR_SWS_0))); 
}

void MCO_Init(){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODE8_1;
	GPIOA->MODER &= ~GPIO_MODER_MODE8_0;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8_0 | GPIO_OSPEEDER_OSPEEDR8_1; 
	
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODE9_1;
	GPIOC->MODER &= ~GPIO_MODER_MODE9_0;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_0 | GPIO_OSPEEDER_OSPEEDR9_1; 
	
	RCC->CFGR &= ~RCC_CFGR_MCO1PRE_Msk;
	RCC->CFGR |= 0b100 << RCC_CFGR_MCO1PRE_Pos;
	RCC->CFGR &= ~RCC_CFGR_MCO2PRE_Msk;
	RCC->CFGR |= 0b100 << RCC_CFGR_MCO2PRE_Pos;
	
	RCC->CFGR |= RCC_CFGR_MCO1_1 | RCC_CFGR_MCO1_0;
}

