#include "stm32f429xx.h"
#include "SPI.h"
#include <stdint.h>

uint16_t SPI1_Read(uint8_t adr){
	(void) SPI1->DR;
	GPIOC->BSRR = GPIO_BSRR_BR4;
	while(!(SPI1->SR & SPI_SR_TXE));
	SPI1->DR = (adr << 8 ) | 0xFF;
	while(!(SPI1->SR & SPI_SR_TXE));
	while((SPI1->SR & SPI_SR_BSY));
	GPIOC->BSRR = GPIO_BSRR_BS4;
	(void) SPI1->DR;
	for(int i=0; i <50; i++);
	GPIOC->BSRR = GPIO_BSRR_BR4;
	SPI1->DR = 0xFFFF;
	while(!(SPI1->SR & SPI_SR_RXNE));
	while((SPI1->SR & SPI_SR_BSY));
	GPIOC->BSRR = GPIO_BSRR_BS4;
	(void) SPI1->DR;
	uint16_t data = SPI1->DR;
	
	
	return data;
}

void SPI1_Init(){
	//SPI1 SCK
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	GPIOB->MODER |= GPIO_MODER_MODE3_1;
	GPIOB->MODER &= ~GPIO_MODER_MODE3_0;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3_0 | GPIO_OSPEEDER_OSPEEDR3_1; 
	GPIOB->AFR[0] &= ~(0xF << 12);
	GPIOB->AFR[0] |= (5 << 12);
	
	//SPI1 MISO
	GPIOB->MODER |= GPIO_MODER_MODE4_1;
	GPIOB->MODER &= ~GPIO_MODER_MODE4_0;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3_0 | GPIO_OSPEEDER_OSPEEDR4_1; 
	GPIOB->AFR[0] &= ~(0xF << 16);
	GPIOB->AFR[0] |= 5 << 16;
	
	//SPI1 MOSI
	GPIOB->MODER |= GPIO_MODER_MODE5_1;
	GPIOB->MODER &= ~GPIO_MODER_MODE5_0;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5_0 | GPIO_OSPEEDER_OSPEEDR5_1; 
	GPIOB->AFR[0] &= ~(0xF << 20);
	GPIOB->AFR[0] |= 5 << 20;

	RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
	SPI1->CR1 |= SPI_CR1_DFF;
	SPI1->CR1 &= ~SPI_CR1_LSBFIRST;	
	SPI1->CR1 |= SPI_CR1_SSM;
	SPI1->CR1 |= SPI_CR1_SSI;
	SPI1->CR1 &= ~SPI_CR1_BR_Msk;
	SPI1->CR1 |= 0b10 << SPI_CR1_BR_Pos;
	SPI1->CR1 |= SPI_CR1_MSTR;
	SPI1->CR1 |= SPI_CR1_CPOL;
	SPI1->CR1 |= SPI_CR1_CPHA;
	SPI1->CR1 |= SPI_CR1_SPE;	
	
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODE4_0;
	GPIOC->MODER &= ~GPIO_MODER_MODE4_1;
	GPIOC->OTYPER &= ~GPIO_OTYPER_OT4;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR4_0 | GPIO_OSPEEDER_OSPEEDR4_1;
	GPIOC->PUPDR &= ~GPIO_PUPDR_PUPD4_Msk;
	
	GPIOC->BSRR |= GPIO_BSRR_BS4;
}

void SPI1_Write(uint8_t adr, uint8_t data){
  GPIOC->BSRR = GPIO_BSRR_BR4;
	 while(!(SPI1->SR & SPI_SR_TXE));
   //(void) SPI2->DR;
	 SPI1->DR = ((0x80 | adr ) << 8) | data;
	 while(!(SPI1->SR & SPI_SR_TXE));
	 while((SPI1->SR & SPI_SR_BSY));
	 GPIOC->BSRR = GPIO_BSRR_BS4;
	for(int i=0; i <5; i++);
	 //(void) SPI2->DR;
}
