#include "stm32f429xx.h"
#include "SPI.h"
#include <stdint.h>

uint16_t SPI1_Read(uint8_t adr){
	(void) SPI1->DR;
	GPIOC->BSRR = GPIO_BSRR_BR4;
	while(!(SPI1->SR & SPI_SR_TXE));
	SPI1->DR = (adr << 8 ) | 0xFF;
	while(!(SPI1->SR & SPI_SR_TXE));
	while((SPI1->SR & SPI_SR_BSY));
	GPIOC->BSRR = GPIO_BSRR_BS4;
	(void) SPI1->DR;
	for(int i=0; i <50; i++);
	GPIOC->BSRR = GPIO_BSRR_BR4;
	SPI1->DR = 0xFFFF;
	while(!(SPI1->SR & SPI_SR_RXNE));
	while((SPI1->SR & SPI_SR_BSY));
	GPIOC->BSRR = GPIO_BSRR_BS4;
	(void) SPI1->DR;
	uint16_t data = SPI1->DR;
	
	
	return data;
}

void SPI1_Init(){
	//SPI1 SCK
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
	GPIOB->MODER |= GPIO_MODER_MODE3_1;
	GPIOB->MODER &= ~GPIO_MODER_MODE3_0;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3_0 | GPIO_OSPEEDER_OSPEEDR3_1; 
	GPIOB->AFR[0] &= ~(0xF << 12);
	GPIOB->AFR[0] |= (5 << 12);
	
	//SPI1 MISO
	GPIOB->MODER |= GPIO_MODER_MODE4_1;
	GPIOB->MODER &= ~GPIO_MODER_MODE4_0;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR3_0 | GPIO_OSPEEDER_OSPEEDR4_1; 
	GPIOB->AFR[0] &= ~(0xF << 16);
	GPIOB->AFR[0] |= 5 << 16;
	
	//SPI1 MOSI
	GPIOB->MODER |= GPIO_MODER_MODE5_1;
	GPIOB->MODER &= ~GPIO_MODER_MODE5_0;
	GPIOB->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR5_0 | GPIO_OSPEEDER_OSPEEDR5_1; 
	GPIOB->AFR[0] &= ~(0xF << 20);
	GPIOB->AFR[0] |= 5 << 20;

	RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
	SPI1->CR1 |= SPI_CR1_DFF;
	SPI1->CR1 &= ~SPI_CR1_LSBFIRST;	
	SPI1->CR1 |= SPI_CR1_SSM;
	SPI1->CR1 |= SPI_CR1_SSI;
	SPI1->CR1 &= ~SPI_CR1_BR_Msk;
	SPI1->CR1 |= 0b10 << SPI_CR1_BR_Pos;
	SPI1->CR1 |= SPI_CR1_MSTR;
	SPI1->CR1 |= SPI_CR1_CPOL;
	SPI1->CR1 |= SPI_CR1_CPHA;
	SPI1->CR1 |= SPI_CR1_SPE;	
	
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODE4_0;
	GPIOC->MODER &= ~GPIO_MODER_MODE4_1;
	GPIOC->OTYPER &= ~GPIO_OTYPER_OT4;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR4_0 | GPIO_OSPEEDER_OSPEEDR4_1;
	GPIOC->PUPDR &= ~GPIO_PUPDR_PUPD4_Msk;
	
	GPIOC->BSRR |= GPIO_BSRR_BS4;
}

void SPI1_Write(uint8_t adr, uint8_t data){
  GPIOC->BSRR = GPIO_BSRR_BR4;
	 while(!(SPI1->SR & SPI_SR_TXE));
   //(void) SPI2->DR;
	 SPI1->DR = ((0x80 | adr ) << 8) | data;
	 while(!(SPI1->SR & SPI_SR_TXE));
	 while((SPI1->SR & SPI_SR_BSY));
	 GPIOC->BSRR = GPIO_BSRR_BS4;
	for(int i=0; i <5; i++);
	 //(void) SPI2->DR;
}

void SPI5_Init(){
	SPI5->CR1 &= ~SPI_CR1_SPE;	
	
	RCC->APB2ENR |= RCC_APB2ENR_SPI5EN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
	
	//CS
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODE1_0;
	GPIOC->MODER &= ~GPIO_MODER_MODE1_1;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR1_0 | GPIO_OSPEEDER_OSPEEDR1_1;
	GPIOC->BSRR = GPIO_BSRR_BS1;
	
	//SKC
	GPIOF->MODER |= GPIO_MODER_MODE7_1;
	GPIOF->MODER &= ~GPIO_MODER_MODE7_0;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR7_0 | GPIO_OSPEEDER_OSPEEDR7_1;
	GPIOF->AFR[0] &= ~GPIO_AFRL_AFSEL7_Msk;
	GPIOF->AFR[0] |= 5 << GPIO_AFRL_AFSEL7_Pos;
	
	//MISO
	GPIOF->MODER |= GPIO_MODER_MODE8_1;
	GPIOF->MODER &= ~GPIO_MODER_MODE8_0;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8_0 | GPIO_OSPEEDER_OSPEEDR8_1;
	GPIOF->AFR[1] &= ~GPIO_AFRH_AFSEL8_Msk;
	GPIOF->AFR[1] |= 5 << GPIO_AFRH_AFSEL8_Pos;
	
	//MOSI
	GPIOF->MODER |= GPIO_MODER_MODE9_1;
	GPIOF->MODER &= ~GPIO_MODER_MODE9_0;
	GPIOF->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR9_0 | GPIO_OSPEEDER_OSPEEDR9_1;
	GPIOF->AFR[1] &= ~GPIO_AFRH_AFSEL9_Msk;
	GPIOF->AFR[1] |= 5 << GPIO_AFRH_AFSEL9_Pos;

	SPI5->CR1 |= SPI_CR1_DFF;
	SPI5->CR1 &= ~SPI_CR1_LSBFIRST;
	SPI5->CR1 |= SPI_CR1_SSM;
	SPI5->CR1 |= SPI_CR1_SSI;
	SPI5->CR1 &= ~SPI_CR1_BR_Msk;
	SPI5->CR1 |= 0b11 << SPI_CR1_BR_Pos;
	SPI5->CR1 |= SPI_CR1_MSTR;
	SPI5->CR1 |= SPI_CR1_CPOL;
	SPI5->CR1 |= SPI_CR1_CPHA;

	SPI5->CR1 |= SPI_CR1_SPE;	
}

uint8_t SPI5_Read(uint8_t reg){ 
    while(!(SPI5->SR & SPI_SR_TXE));
		GPIOC->BSRR = GPIO_BSRR_BR1;
    SPI5->DR = ((reg | (1 << 7))<< 8) | 0xFF;
		while(!(SPI5->SR & SPI_SR_TXE));	
    while(SPI5->SR & SPI_SR_BSY);
		GPIOC->BSRR = GPIO_BSRR_BS1;
		return (uint8_t)SPI5->DR;  
}

void SPI5_Write(uint8_t reg, uint8_t data){ 
    while(!(SPI5->SR & SPI_SR_TXE));
		GPIOC->BSRR = GPIO_BSRR_BR1;  
		SPI5->DR = (reg<< 8) | data;                            
    while(!(SPI5->SR & SPI_SR_TXE));
		while(SPI5->SR & SPI_SR_BSY);
		GPIOC->BSRR = GPIO_BSRR_BS1;
		(void) SPI5->DR;
}
